### ISSUE TITLE
Cursor maps incorrectly

### ISSUE THREAD

**Issue by TheChymera** [pauldmccarthy/fsleyes#37] opened 2020-01-16 21:39 UTC
When I try to navigate through the image space with the mouse, the crosshair and view centering is displaced towards the bottom and left. This happens in all 3 planar views, and happens with the current version (`0.32.0`) as well as with `0.27.3`.

See video demonstration [here](http://chymera.eu/debug/fsleyes/cursor.mp4).

**Comment by pauldmccarthy** [comment] 2020-01-16 23:07
Your video link is returning a 404, but do you mean that you are being affected by [this](https://github.com/pauldmccarthy/fsleyes/issues/34)?

**Comment by TheChymera** [comment] 2020-01-17 02:54
Apologies. I fixed the link. Could you have a look? I'll also be investigating this with 1x when I'm back at the office tomorrow.

**Comment by TheChymera** [comment] 2020-01-17 16:06
I was able to confirm that this is in fact resulting from the DPI setting. At 1x the issue disappears, and the images are better positioned inside the window. Very strange, if you say this is a further upstream issue, since I never encountered it with other software. Any idea if this might be saved soon? Since me and a lot of my colleagues use hiDPI screens (not as much by preference but because this is what many high-end laptops come with nowadays), this is a bit of a problem.

**Comment by pauldmccarthy** [comment] 2020-01-20 04:19
So yes this is a duplicate of #34 - closing this issue, and moving the conversation there.

**Closed by pauldmccarthy** 2020-01-20 04:19 UTC
