### ISSUE TITLE
image was shown in the left bottom conner

### ISSUE THREAD

**Issue by pcasl** [pauldmccarthy/fsleyes#54] opened 2020-06-24 20:55 UTC
fsleye was install on MacOS through pip3, but the when open images, it only show the image in the left bottom corner of the window (25%). 

But when moving the mouse around, the location is still in the normal view. When print to jpeg, it is also right. So, it sounds like a display problem. Any suggestions? 

<img width="1125" alt="Screen Shot 2020-06-24 at 4 53 25 PM" src="https://user-images.githubusercontent.com/45406630/85626612-4975bd00-b63b-11ea-83c4-515938c55547.png">

**Comment by pauldmccarthy** [comment] 2020-06-24 22:10
@pcasl can you re-install FSLeyes like so:

```pip install fsleyes[extras]```

and see if that fixes the problem?

Retina support requires some extra libraries which are not installed by default when installing FSLeyes via pip.

**Comment by pcasl** [comment] 2020-06-24 22:14
@pauldmccarthy, thanks for your help. Some how it is not found.
pip3 install fsleyes[extras]
zsh: no matches found: fsleyes[extras]

**Comment by pauldmccarthy** [comment] 2020-06-25 07:31
zsh doesn't like square brackets - could you re-run the same command like this:
```
pip3 install "fsleyes[extras]"
```

**Comment by pcasl** [comment] 2020-06-25 10:52
There is an error

pip3 install "fsleyes[extras]"
Requirement already satisfied: fsleyes[extras] in ./fsleyes-virtualenv/lib/python3.7/site-packages (0.33.2)
Requirement already satisfied: fslpy>=3.1 in ./fsleyes-virtualenv/lib/python3.7/site-packages (from fsleyes[extras]) (3.2.1)
Requirement already satisfied: matplotlib>=1.5.1 in ./fsleyes-virtualenv/lib/python3.7/site-packages (from fsleyes[extras]) (3.2.2)
Requirement already satisfied: numpy>=1.14 in ./fsleyes-virtualenv/lib/python3.7/site-packages (from fsleyes[extras]) (1.19.0)
Requirement already satisfied: Jinja2==2.* in ./fsleyes-virtualenv/lib/python3.7/site-packages (from fsleyes[extras]) (2.11.2)
Requirement already satisfied: fsleyes-widgets>=0.8.4 in ./fsleyes-virtualenv/lib/python3.7/site-packages (from fsleyes[extras]) (0.9.0)
Requirement already satisfied: pyparsing==2.* in ./fsleyes-virtualenv/lib/python3.7/site-packages (from fsleyes[extras]) (2.4.7)
Requirement already satisfied: Pillow>=3.2.0 in ./fsleyes-virtualenv/lib/python3.7/site-packages (from fsleyes[extras]) (7.1.2)
Requirement already satisfied: fsleyes-props>=1.6.7 in ./fsleyes-virtualenv/lib/python3.7/site-packages (from fsleyes[extras]) (1.7.0)
Requirement already satisfied: wxPython>=3.0.2.0 in ./fsleyes-virtualenv/lib/python3.7/site-packages (from fsleyes[extras]) (4.1.0)
Requirement already satisfied: nibabel>=2.3 in ./fsleyes-virtualenv/lib/python3.7/site-packages (from fsleyes[extras]) (3.1.0)
Requirement already satisfied: six==1.* in ./fsleyes-virtualenv/lib/python3.7/site-packages (from fsleyes[extras]) (1.15.0)
Requirement already satisfied: setuptools in ./fsleyes-virtualenv/lib/python3.7/site-packages (from fsleyes[extras]) (41.2.0)
Requirement already satisfied: PyOpenGL>=3.1.0 in ./fsleyes-virtualenv/lib/python3.7/site-packages (from fsleyes[extras]) (3.1.5)
Requirement already satisfied: scipy>=0.18 in ./fsleyes-virtualenv/lib/python3.7/site-packages (from fsleyes[extras]) (1.5.0)
Collecting trimesh>=2.37.29; extra == "extras" (from fsleyes[extras])
  Using cached https://files.pythonhosted.org/packages/0a/2d/071cbfed35607e42b732d7135cfb7bb4ca9ee6b64a9bd16888e50cf52eac/trimesh-3.7.4-py3-none-any.whl
Collecting ipykernel>=4.8; extra == "extras" (from fsleyes[extras])
  Using cached https://files.pythonhosted.org/packages/61/18/f2350f0396fca562c22f880e25d668eaf6de129b6a56bf5b6786796a12e1/ipykernel-5.3.0-py3-none-any.whl
Collecting xnat>=0.3.3; extra == "extras" (from fsleyes[extras])
  Using cached https://files.pythonhosted.org/packages/83/f4/2b0ad41442c4f04173601cb406f764311525463666c502575e6dff40676b/xnat-0.3.24-py3-none-any.whl
Collecting ipython>=5; extra == "extras" (from fsleyes[extras])
  Using cached https://files.pythonhosted.org/packages/aa/e8/47fda10c3ab103d9d4a667b40da9afd542c4e50aeb00c861b4eee5bb4e8f/ipython-7.15.0-py3-none-any.whl
Collecting rtree>=0.8.3; extra == "extras" (from fsleyes[extras])
  Using cached https://files.pythonhosted.org/packages/56/6f/f1e91001d5ad9fa9bed65875152f5a1c7955c5763168cae309546e6e9fda/Rtree-0.9.4.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Users/lizhao/fsleyes-virtualenv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/p0/hb5d4gz96bs8gkdvg4wj1px40000gn/T/pip-install-d5cbcve_/rtree/setup.py'"'"'; __file__='"'"'/private/var/folders/p0/hb5d4gz96bs8gkdvg4wj1px40000gn/T/pip-install-d5cbcve_/rtree/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/p0/hb5d4gz96bs8gkdvg4wj1px40000gn/T/pip-install-d5cbcve_/rtree/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/p0/hb5d4gz96bs8gkdvg4wj1px40000gn/T/pip-install-d5cbcve_/rtree/setup.py", line 3, in <module>
        import rtree
      File "/private/var/folders/p0/hb5d4gz96bs8gkdvg4wj1px40000gn/T/pip-install-d5cbcve_/rtree/rtree/__init__.py", line 1, in <module>
        from .index import Rtree
      File "/private/var/folders/p0/hb5d4gz96bs8gkdvg4wj1px40000gn/T/pip-install-d5cbcve_/rtree/rtree/index.py", line 6, in <module>
        from . import core
      File "/private/var/folders/p0/hb5d4gz96bs8gkdvg4wj1px40000gn/T/pip-install-d5cbcve_/rtree/rtree/core.py", line 143, in <module>
        rt.Error_GetLastErrorNum.restype = ctypes.c_int
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
        func = self.__getitem__(name)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: dlsym(RTLD_DEFAULT, Error_GetLastErrorNum): symbol not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by pauldmccarthy** [comment] 2020-06-25 10:55
My guess is that you don't have spatialindex installed - this cannot be installed via pip, as it is a non-python dependency. You could install it via homebrew if you have that.

Honestly, I would recommend using conda to install FSLeyes rather than pip - installing via pip is recommended for advanced/development users.

**Comment by pcasl** [comment] 2020-06-25 11:22
Thank you so much for your help! The conda one works.

For the pip installation, I installed the spatialindex and reinstalled the "fsleyes[extras]", but still the same HDI problem.

**Comment by pauldmccarthy** [comment] 2020-06-25 11:39
I would recommend sticking with the conda installation, as it generally works out of the box, without having to worry about optional/non-python dependencies.

I'll leave this issue open though - next time I have access to a mac, I'll try and reproduce your problem.

**Comment by pauldmccarthy** [comment] 2020-07-14 16:34
It turns out that this is due to a change in wxPython - with older versions of wxPython on macOS, I had to explicitly scale the GL canvas. But as of wxpython 4.1.0, this seems to happen automatically. So I'll need to adjust the logic in FSLeyes to use a different scaling strategy depending on which version of wxpython is installed.

**Comment by pauldmccarthy** [comment] 2020-07-16 09:59
This should be fixed as of FSLeyes 0.34.2 for pip-based installations. Feel free to re-open if you still have trouble.

**Closed by pauldmccarthy** 2020-07-16 09:59 UTC
