### ISSUE TITLE
fsleyes fails to start

### ISSUE THREAD

**Issue by cathbridges** [pauldmccarthy/fsleyes#66] opened 2021-01-31 21:27 UTC
I am trying to use a FSLeyes GUI with AxonDeepSeg in a virtual environment. I'm on a Mac using MacOS Mojave. I started by opening a new issue with AxonDeepSeg #neuropoly/axondeepseg#446 

We found that even with just FSLeyes in a new virtual environment, the application does not open. The only thing that happens is a python window pops up and when I force quit, I see this:
(installation_test) Millies-Mac:~ catherinebridges$ fsleyes
/Users/catherinebridges/miniconda/envs/installation_test/bin/pythonw: line 3: 64410 Terminated: 15          /Users/catherinebridges/miniconda/envs/installation_test/python.app/Contents/MacOS/python "$@"

Have you seen this happen before? Any tips on how to fix it? Please let me know if you need more information.

**Comment by Stoyan-I-A** [comment] 2021-01-31 21:48
Just adding a few details, this is the instructions I gave to this user in order to install and launch FSLeyes:

> 1. Open a terminal and create a new virtual environment using conda:
> `conda create -n installation_test python=3.7`
> 2. Activate the environment:
> `conda activate installation_test`
> 3. Install FSLeyes using conda-forge:
> `yes | conda install -c conda-forge fsleyes`
> 4. Try to launch FSLeyes:
> `fsleyes`

No other error messages appear on the user's console.

Since this issue doesn't involve our software (AxonDeepSeg), I thought it would be right to redirect the user here.

**Comment by pauldmccarthy** [comment] 2021-02-01 10:00
Hi @cathbridges and @Stoyan-I-A, I haven't seen this before, but my guess is that a another Python environment, or user-installed python libraries, is interfering with FSLeyes.

Can you give me the output of the following commands:

```bash
env
python -m site --user-site
# the following command might print an error
ls $(python -m site --user-site) 
```

**Comment by pauldmccarthy** [comment] 2021-02-01 10:07
Also, could you try running FSLeyes again, and then in a new terminal, run `top`? Is there any CPU activity going on while FSLeyes is hanging?

**Comment by cathbridges** [comment] 2021-02-01 14:52
`env`
PERLBREW_SHELLRC_VERSION=0.88
MANPATH=/Users/catherinebridges/perl5/perlbrew/perls/perl-5.28.0/man:/Library/Frameworks/Python.framework/Versions/3.8/share/man:/usr/local/share/man:/usr/share/man:/opt/X11/share/man:/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/share/man:/Library/Developer/CommandLineTools/usr/share/man
PERLBREW_VERSION=0.88
TERM_PROGRAM=Apple_Terminal
PERLBREW_PERL=perl-5.28.0
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/k2/yhp7b6kd1nbbmvyqq0dj02j80000gn/T/
CONDA_SHLVL=2
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.xBjkqg71Nx/Render
CONDA_PROMPT_MODIFIER=(ads_venv) 
TERM_PROGRAM_VERSION=421.2
TERM_SESSION_ID=B8121656-77B5-43B0-B7CD-7A44522C3595
USER=catherinebridges
CONDA_EXE=/Users/catherinebridges/miniconda/bin/conda
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.xDz7dmSABU/Listeners
PERLBREW_ROOT=/Users/catherinebridges/perl5/perlbrew
_CE_CONDA=
CONDA_PREFIX_1=/Users/catherinebridges/opt/anaconda3
PATH=/Users/catherinebridges/miniconda/envs/ads_venv/bin:/Users/catherinebridges/opt/anaconda3/condabin:/Users/catherinebridges/perl5/perlbrew/bin:/Users/catherinebridges/perl5/perlbrew/perls/perl-5.28.0/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Users/catherinebridges/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
CONDA_PREFIX=/Users/catherinebridges/miniconda/envs/ads_venv
PWD=/Users/catherinebridges/axondeepseg
LANG=en_US.UTF-8
PERLBREW_HOME=/Users/catherinebridges/.perlbrew
XPC_FLAGS=0x0
_CE_M=
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/catherinebridges
PERLBREW_MANPATH=/Users/catherinebridges/perl5/perlbrew/perls/perl-5.28.0/man
CONDA_PYTHON_EXE=/Users/catherinebridges/miniconda/bin/python
PERLBREW_PATH=/Users/catherinebridges/perl5/perlbrew/bin:/Users/catherinebridges/perl5/perlbrew/perls/perl-5.28.0/bin
LOGNAME=catherinebridges
CONDA_DEFAULT_ENV=ads_venv
DISPLAY=/private/tmp/com.apple.launchd.rLlbOB2phn/org.macosforge.xquartz:0
_=/usr/bin/env
OLDPWD=/Users/catherinebridges
`
python -m site --user-site`
/Users/catherinebridges/.local/lib/python3.7/site-packages

`ls $(python -m site --user-site)`
no output or errors

`top`
Processes: 311 total, 2 running, 309 sleeping, 1419 threads            09:52:05
Load Avg: 2.46, 2.77, 2.36  CPU usage: 9.39% user, 6.74% sys, 83.85% idle
SharedLibs: 202M resident, 61M data, 63M linkedit.
MemRegions: 44405 total, 2994M resident, 149M private, 1328M shared.
PhysMem: 7992M used (1266M wired), 199M unused.
VM: 1372G vsize, 1370M framework vsize, 383(0) swapins, 383(0) swapouts.
Networks: packets: 338619/106M in, 68447/11M out.
Disks: 545133/15G read, 176272/5327M written.

PID    COMMAND      %CPU TIME     #TH   #WQ  #PORT MEM    PURG   CMPRS  PGRP
12541  mdworker_sha 0.0  00:00.10 5     2    63+   4464K+ 0B     0B     12541
12534  mdworker_sha 0.0  00:00.05 3     1    56    3640K  0B     0B     12534
12531  mdworker_sha 0.0  00:00.06 3     1    50    2904K  0B     0B     12531
12530  mdworker_sha 0.0  00:00.06 3     1    50    2928K  0B     0B     12530
12529  mdworker_sha 0.0  00:00.06 3     1    50    2956K  0B     0B     12529
12528  mdworker_sha 0.0  00:00.06 3     1    50    2996K  0B     0B     12528
12527  mdworker_sha 0.0  00:00.06 3     1    47    2868K  0B     0B     12527
12520  top          3.1  00:01.82 1/1   0    32+   2628K  0B     0B     12520
12493  bash         0.0  00:00.03 1     0    21    964K   0B     0B     12493
12492  login        0.0  00:00.09 2     1    30    1008K  0B     0B     12492
12424  python       1.7  00:03.26 6     1    64    59M    0B     0B     12423
12423  bash         0.0  00:00.00 1     0    10    496K   0B     0B     12423
12317  UsageTrackin 0.0  00:00.09 2     1    56    2144K  28K    0B     12317
12290  plugin-conta 0.0  00:01.67 19    1    121   30M    0B     0B     532

**Comment by pauldmccarthy** [comment] 2021-02-02 11:03
Nothing in your environment really stands out as a potential problem. Just to be sure, what do the following commands return?

```
which python
which pythonw 
which python.app
which fsleyes
cat $(which fsleyes)
```

Does FSLeyes start when you run it via any of these variants?

```
python -m fsleyes
python.app -m fsleyes
pythonw -m fsleyes
python -I $(which fsleyes)
python.app -I $(which fsleyes)
pythonw -I $(which fsleyes)
```

**Comment by pauldmccarthy** [comment] 2021-02-02 12:40
@cathbridges I managed to reproduce this (by remotely logging in to an old mac that I still have access to) - there seems to be a problem with the latest version of `wxpython`, which was released about 2 weeks ago. Downgrading to an older version of `wxpython` fixed things for me:

`conda install -c conda-forge "wxpython=4.0.*"`

**Comment by pauldmccarthy** [comment] 2021-02-02 13:01
xref https://github.com/conda-forge/wxpython-feedstock/issues/70

**Comment by cathbridges** [comment] 2021-02-02 17:01
> @cathbridges I managed to reproduce this (by remotely logging in to an old mac that I still have access to) - there seems to be a problem with the latest version of `wxpython`, which was released about 2 weeks ago. Downgrading to an older version of `wxpython` fixed things for me:
> 
> `conda install -c conda-forge "wxpython=4.0.*"`

This fixed it! Thank you so much!

**Comment by Stoyan-I-A** [comment] 2021-03-30 22:16
I suggest closing this issue since the user problem has been fixed and https://github.com/conda-forge/wxpython-feedstock/issues/70 has been closed.

**Comment by pauldmccarthy** [comment] 2021-03-31 08:47
@Stoyan-I-A Thanks - I'm preparing a new FSLeyes release, at which point I was intending to close all pending issues :)

**Closed by pauldmccarthy** 2021-03-31 08:47 UTC
