### ISSUE TITLE
GLXBadCurrentWindow in 0.33.1

### ISSUE THREAD

**Issue by dmd** [pauldmccarthy/fsleyes#53] opened 2020-06-22 22:38 UTC
When launching fsleyes under fsl 6.0.3 (having updated using `$FSLDIR/fslpython/bin/conda update -n fslpython -c conda-forge --update-deps fsleyes`), I get:

```
$ $FSLDIR/bin/fsleyes --version
fsleyes/FSLeyes version 0.33.1
$ $FSLDIR/bin/fsleyes
The program 'fsleyes' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadCurrentWindow'.
  (Details: serial 1078 error_code 165 request_code 149 minor_code 115)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

I have no problems under 0.27.3+build0.

**Comment by dmd** [comment] 2020-06-22 22:50
This is when connecting from a Mac using XQuartz 2.7.11.

**Comment by pauldmccarthy** [comment] 2020-06-23 07:04
Hi @dmd is there a chance that you are affected by this troubleshooting issue? 

https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/userdoc/latest/troubleshooting.html#xquartz-fsleyes-doesn-t-start-and-just-shows-an-error

**Comment by dmd** [comment] 2020-06-23 12:08
Nope, that's a separate issue - I checked that I'm set to true (and if I were set to false, 0.27 would have problems too).

**Comment by pauldmccarthy** [comment] 2020-06-23 15:24
Unfortunately I don't have access to a mac, so I can't reproduce this problem. Would you be able to test whether the problem occurs with FSLeyes version 0.32.3? You should be able install it like so:

```
FSLDIR/fslpython/bin/conda update -n fslpython -c conda-forge install fsleyes==0.32.3
```

**Comment by dmd** [comment] 2020-06-23 16:03
Assuming what you meant was:

```
$FSLDIR/fslpython/bin/conda install -n fslpython -c conda-forge fsleyes=0.32.3
```

Which resulted in:

```
$ $FSLDIR/bin/fsleyes --version
fsleyes/FSLeyes version 0.32.3
```

The problem does *not* occur under 0.32.3.

**Comment by pauldmccarthy** [comment] 2020-06-24 08:58
Ok, this means that I have broken something while trying to fix something else. Unfortunately I'm not sure when I'll next have acess to a mac (working from home for the forseeable future), so I would suggest sticking with 0.32.3 for the time being.

**Comment by dmd** [comment] 2020-06-24 12:01
Do you know what version #48 was fixed in?

**Comment by pauldmccarthy** [comment] 2020-06-24 12:35
That was fixed in the underlying [fslpy](https://github.com/pauldmccarthy/fslpy) library in version 3.0.1. Unfortunately FSLeyes 0.32.3 won't work with fslpy >=3, due to dependence on some deprecated functionality that was removed.

But I *think* the `GLXBadCurrentWindow` issue you are experiencing was introduced in FSLeyes 0.33.1 So, fingers crossed, you should be able to install FSLeyes 0.33.0 and the latest version of fslpy.

If this doesn't work, I can look at backporting the #48 fix to fslpy 2.9.x

**Comment by pauldmccarthy** [comment] 2020-07-08 18:20
I think I've fixed this issue in the current master - would you be able to test it? You should just be able to do this:
```
git clone https://github.com/pauldmccarthy/fsleyes.git
export PYTHONPATH=`pwd`/fsleyes
$FSLDIR/bin/fslpython -m fsleyes
```

Or, I'll probably release a new version tomorrow, so you can wait until then if you like.

**Comment by dmd** [comment] 2020-07-08 19:54
That seems to have solved the display issue - as in, fsleyes now launches successfully - but now when I try to open a .nii.gz, I get "Index must be completely built in order to seek from SEEK_END", which I'd not gotten in previous versions.

**Comment by pauldmccarthy** [comment] 2020-07-08 20:46
*That* error can be resolved by upgrading your versions of nibabel and/or indexed_gzip.

Good to hear though, thanks for getting back to me - I should have 0.34.0 out tomorrow.

**Comment by dmd** [comment] 2020-07-09 15:12
Not sure if this is just me being dumb or what, but, starting from before updating to 0.34.0, here's what happened. Assume in each step that "update" means to run:

```
sudo $FSLDIR/fslpython/bin/conda update -n fslpython -c conda-forge \
     --update-deps PACKAGENAME
```

* update fsleyes
   * result: SEEK_END error as mentioned above
* update nibabel and indexed_gzip
   * result: fsleyes exits immediately on launch - return code 0, but no GUI ever pops up and nothing printed to stdout, just like in #58 
* update fsleyes *again*
   * success!

**Comment by pauldmccarthy** [comment] 2020-07-09 16:14
Strange ... my only thought is that this could be caused by the fact that the `$FSLDIR/fslpython` environment specification is kind of broken, in that it prioritises trying to install from the anaconda `defaults` channel, when it should actually prioritise `conda-forge`. So maybe on the broken attempt, it has inadvertently clobbered some `conda-forge` packages with older `defaults` versions? 

If you can reproduce the problem, could you generate listings of a broken, and of a fixed environment? You can use this command:

```$FSLDIR/fslpython/bin/conda list -n fslpython --show-channel-urls```

**Comment by pauldmccarthy** [comment] 2020-07-09 16:16
Oh, and looking at #58 again, the `fsleyes` command actually runs a filter on stdout/stderr to suppress a whole bunch of warnnings originating from GTK that I have no control over. If you can reproduce the crash, you can run the `$FSLDIR/fslpython/envs/fslpython/bin/fsleyes_unfiltered` command which does not perform the filtering.

**Comment by pauldmccarthy** [comment] 2020-07-14 14:16
@dmd I am assuming that this issue (and #58) is resolved - feel free to re-open if you are still having problems

**Closed by pauldmccarthy** 2020-07-14 14:16 UTC

**Comment by dmd** [comment] 2021-04-14 00:36
This seems to be happening again under 6.0.4!

**Comment by pauldmccarthy** [comment] 2021-04-14 08:36
Hi @dmd, I have made a few changes which will hopefully resolve this once and for all. They're currently in the master branch, and I'm hoping to release a new version in the next week or so. If this is really bugging you, and you'd like to run a development version, I can give you some instructions to get set up.

**Comment by dmd** [comment] 2021-04-28 12:22
Is this happening soon?

**Comment by pauldmccarthy** [comment] 2021-04-28 15:15
@dmd yes - sorry - the latest version (1.0.3) is available on conda-forge and pypi - please let me know if updating resolves the issue

**Comment by dmd** [comment] 2021-04-28 15:40
Nope, no change.

```
ddrucker@micc ~
❯ /cm/shared/fsl-6.0.4/bin/fsleyes -h | head -1
FSLeyes version 1.0.3

ddrucker@micc ~ took 3s
❯ /cm/shared/fsl-6.0.4/bin/fsleyes
The program 'fsleyes' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 1032 error_code 2 request_code 149 minor_code 24)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

ddrucker@micc ~ took 3s
✖1 ❯
```

**Comment by dmd** [comment] 2021-04-28 15:45
This appears to work! I'll ask some of my users to test, but it works for me.

**Comment by pauldmccarthy** [comment] 2021-04-28 15:51
Great! Let me know how your users get on..

**Comment by dmd** [comment] 2021-04-28 16:16
Looks like it works for the person who was complaining. I think this is good now.

**Comment by Rokujo001** [comment] 2021-06-16 10:14
Hi, I hope someone could hep me. I'm using a linux subsystem (Ubuntu 18.04) on windows
I get this error: 
`The program 'fsleyes' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadContext'.
  (Details: serial 7215 error_code 154 request_code 149 minor_code 5)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)`
   
   I updated everything (the only thing I can't update is Conda for some reason)
   FLSeyes version 1.1.0.dev0

What should I do?

Thanks!
