### ISSUE TITLE
FSLeyes cannot create window (under wayland)

### ISSUE THREAD

**Issue by TheChymera** [pauldmccarthy/fsleyes#45] opened 2020-03-24 23:41 UTC
I am trying to launch FSLeyes, and I get a failure from wxGTK, any idea what's going on?

```
chymera@silenthost ~ $ fsleyes

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/fsleyes/gl/__init__.py", line 724, in __createWXGLCanvas
    self.__canvas.SetSize((0, 0))
wx._core.wxAssertionError: C++ assertion "m_widget" failed at /var/tmp/portage/x11-libs/wxGTK-3.0.4-r302/work/wxWidgets-3.0.4/src/gtk/window.cpp(2875) in DoSetSize(): invalid window

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/fsleyes/main.py", line 562, in initialise
    fslgl.getGLContext(parent=splash, ready=realCallback)
  File "/usr/lib64/python3.6/site-packages/fsleyes/gl/__init__.py", line 463, in getGLContext
    thismod._glContext = GLContext(**kwargs)
  File "/usr/lib64/python3.6/site-packages/fsleyes/gl/__init__.py", line 609, in __init__
    self.__createWXGLCanvas()
  File "/usr/lib64/python3.6/site-packages/fsleyes/gl/__init__.py", line 732, in __createWXGLCanvas
    self.__canvas.SetSize((0, 0))
wx._core.wxAssertionError: C++ assertion "m_widget" failed at /var/tmp/portage/x11-libs/wxGTK-3.0.4-r302/work/wxWidgets-3.0.4/src/gtk/window.cpp(2875) in DoSetSize(): invalid window
```

This may be related to this machine using wayland.

**Comment by pauldmccarthy** [comment] 2020-03-29 10:17
Until wxpython has full support for wayland, FSLeyes won't. This is a duplicate of #22 - closing.

**Closed by pauldmccarthy** 2020-03-29 10:17 UTC
